sudo: required
services:
- docker
env:
  global:
    # Ensure the install happens without prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: node_js
node_js:
- '6'
before_install:
- npm install
install:
- webpack --progress
# Build Docker Images
- docker build -t cloudboost/accounts:2.0.$TRAVIS_BUILD_NUMBER .
- docker build -t cloudboost/accounts:latest .
after_success:
# Docker Deploy.
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login --username $DOCKERUSERNAME --password $DOCKERPASSWORD --email $DOCKEREMAIL;
  docker push cloudboost/accounts:2.0.$TRAVIS_BUILD_NUMBER;
  docker push cloudboost/accounts:latest;
  fi

#Notify Team on Slack
notifications:
  slack: cloudboost:gm7nWJDLDtBRyF75VKLKOoMW
